name: CI JAVA
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Token de SonarCloud para el análisis'
        required: true
      SNYK_TOKEN:
        description: 'Token de Snyk para el análisis'
        required: true
    inputs:
      workflow:
        type: string
        required: true
      releaseId:
        type: string
        required: false
        default: ""
      projectId:
        type: string
        required: false
        default: ""
      region:
        type: string
        required: false
        default: "DIGITAL"
      csild:
        type: string
        required: false
        default: ""

      # Bloques anidados como JSON string
      sourceCode_json:
        type: string
        required: false
        default: |
          {"projectStream":"master","projectModule":"","repositoryInstance":"Github"}
      build_json:
        type: string
        required: false
        default: |
          {"dependencyResolutionRepo":"artifactory","printVerboseLog":false,"deployLibraries":false,"pomFileLocation":".","packageIncludes":"","jenkinsAdditionalFolder":"content","svnProfiles":"","tibcoBW":{"stpVersion":""},"deployToPkgArchive":true}
      staticCodeAnalysis_json:
        type: string
        required: false
        default: |
          {"blackDuck":{"RELEASENAME":"","BD_ARCHER_COMPONENT":"","SCAN_WF":"","BD_SOURCE_SYSTEM":""},
           "checkmarx":{"CHECKMARX_CONFIG_CMPNAME":"","CHECKMARX_ENV":"","SCAN_WF":"","CHECKMARX_CX_TEAMNAME":"","CHECKMARX_ARCHER_BASE_CMPNAME":"","CHECKMARX_TYPE_WF_SCAN":"","RELEASENAME":""},
           "sonarQube":{"sonarExcludes":"","sonarLanguage":""},
           "appscan":{"archerRecord":""}}
      threshold_json:
        type: string
        required: false
        default: |
          {"unitTestSuccessDensity":0,"securityRating":0,"techDebtRatio":0,"reliabilityRating":0,"unitTestCoverage":0}
      deploy_json:
        type: string
        required: false
        default: |
          {"NA":{"rlmExecute":false,"rlmEnvironment":"","rlmParams":"","rlmUIParams":"","rlmTemplate":""},
           "SWSDEVTEST":{"rlmExecute":true,"rlmEnvironment":"","rlmParams":"","rlmUIParams":"","rlmTemplate":""}}

      postBuildDeployEnv:
        type: string
        required: false
        default: ""

jobs:
  pipeline-ci-java:
    runs-on: ubuntu-latest
    # Permisos necesarios para firmar (ej. con Sigstore) y
    # publicar en el registro de GitHub (GHCR)
    permissions:
      contents: read
      packages: write # Para 'docker push' a GHCR
      id-token: write # Para autenticación 'keyless' de Sigstore/cosign
      security-events: write # Requerido para subir resultados SARIF
    env:
      # escala simple
      WORKFLOW: ${{ inputs.workflow }}
      RELEASE_ID: ${{ inputs.releaseId }}
      PROJECT_ID: ${{ inputs.projectId }}
      REGION: ${{ inputs.region }}
      CSILD: ${{ inputs.csild }}

      # parseo JSON a nivel de env cuando conviene (campos más usados)
      SOURCE_PROJECT_STREAM: ${{ fromJSON(inputs.sourceCode_json).projectStream }}
      SOURCE_PROJECT_MODULE: ${{ fromJSON(inputs.sourceCode_json).projectModule }}
      SOURCE_REPO_INSTANCE: ${{ fromJSON(inputs.sourceCode_json).repositoryInstance }}

      BUILD_VERBOSE: ${{ fromJSON(inputs.build_json).printVerboseLog }}
      BUILD_DEPLOY_LIBS: ${{ fromJSON(inputs.build_json).deployLibraries }}
      BUILD_POM: ${{ fromJSON(inputs.build_json).pomFileLocation }}
      BUILD_DEPLOY_TO_ARCHIVE: ${{ fromJSON(inputs.build_json).deployToPkgArchive }}

      # thresholds
      THRESH_UT_SUCCESS: ${{ fromJSON(inputs.threshold_json).unitTestSuccessDensity }}
      THRESH_SEC: ${{ fromJSON(inputs.threshold_json).securityRating }}
      THRESH_TD: ${{ fromJSON(inputs.threshold_json).techDebtRatio }}
      THRESH_REL: ${{ fromJSON(inputs.threshold_json).reliabilityRating }}
      THRESH_COV: ${{ fromJSON(inputs.threshold_json).unitTestCoverage }}

      POST_BUILD_DEPLOY_ENV: ${{ inputs.postBuildDeployEnv }}

    steps:
      - name: 2. Checkout del código (del repo que llama)
        uses: actions/checkout@v4
        with:
          # ESTA ES LA LÍNEA MÁS IMPORTANTE
          # Le dice al checkout que baje el código del "Middleware"
          # y no el del "CI/CD".
          repository: ${{ github.repository }}
          # Le dice qué commit exacto bajar
          ref: ${{ github.sha }}
          # Necesario para SonarCloud
          fetch-depth: 0 

      # Instala la Snyk CLI
      - name: 4. Instalar Snyk CLI
        uses: snyk/actions/setup@master

      # 5. Ejecutar Snyk Open Source (Dependencias)
      - name: 5. Run Snyk Open Source Scan
        run: |
          snyk test --sarif-file-output=snyk-oss.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 8. Subir los resultados a GitHub
      - name: 8. Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Combina todos los reportes SARIF
          sarif_file: |
            snyk-oss.sarif